codereview/apps/about/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template



urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "about/about.html"}, name="about"),
    
    url(r"^terms/$", direct_to_template, {"template": "about/terms.html"}, name="terms"),
    url(r"^privacy/$", direct_to_template, {"template": "about/privacy.html"}, name="privacy"),
    url(r"^dmca/$", direct_to_template, {"template": "about/dmca.html"}, name="dmca"),
    
    url(r"^what_next/$", direct_to_template, {"template": "about/what_next.html"}, name="what_next"),
)

codereview/apps/annotation/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns("",
  url('(?P<content_type_str>[-\w]+)/(?P<obj_id>\d+)/annotate_form/(?P<position>\d+)/',
      'annotation.views.annotate_form',
      name='annotate-form'),
)

codereview/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from account.openid_consumer import PinaxConsumer



handler500 = "pinax.views.server_error"


if settings.ACCOUNT_OPEN_SIGNUP:
    signup_view = "account.views.signup"
else:
    signup_view = "signup_codes.views.signup"


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {
        "template": "homepage.html",
    }, name="home"),
    
    url(r"^admin/invite_user/$", "signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^account/signup/$", signup_view, name="acct_signup"),
    
    (r"^about/", include("about.urls")),
    (r"^account/", include("account.urls")),
    (r"^openid/(.*)", PinaxConsumer()),
    (r"^profiles/", include("basic_profiles.urls")),
    (r"^notices/", include("notification.urls")),
    (r"^announcements/", include("announcements.urls")),
    (r'^mypaste/', include('dpaste.urls')),
    (r'^annotations/', include('annotation.urls')),                       
    (r"^admin/", include(admin.site.urls)),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        (r"", include("staticfiles.urls")),
    )

codereview/apps/about/models.py
from django.db import models

# Create your models here.

codereview/apps/annotation/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.generic import GenericForeignKey

class Annotation(models.Model):
    commentor = models.ForeignKey(User)
    comment = models.TextField()
    content_type = models.ForeignKey(ContentType)
    object_id = models.IntegerField()
    entity = GenericForeignKey()
    date_added = models.DateTimeField(default=datetime.datetime.now)
    position = models.CharField(max_length=10)
    
    def __unicode__(self):
        return "Comment for %s on %s" % (self.entity, self.position)
    

codereview/apps/annotation/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from annotation.models import Annotation

class AnnotationModelForm(forms.ModelForm):
    commentor = forms.ModelChoiceField(widget=widgets.HiddenInput, queryset=User.objects.all())
    content_type = forms.ModelChoiceField(widget=widgets.HiddenInput, queryset=ContentType.objects.all())
    object_id = forms.IntegerField(widget=widgets.HiddenInput)
    date_added = forms.DateTimeField(widget=widgets.HiddenInput, required=False)
    position = forms.CharField(widget=widgets.HiddenInput)
    class Meta:
        model = Annotation

codereview/apps/about/views.py
# Create your views here.

codereview/apps/annotation/views.py
import datetime
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from annotation.models import Annotation
from annotation.forms import AnnotationModelForm
from django.utils import simplejson

def annotation_list(request, content_type_str, obj_id, position):
    ct = ContentType.objects.get(name=content_type_str)
    obj = ct.model_class().objects.get(id=obj_id)
    ann_list = Annotation.objects.filter(content_type=ct, object_id=obj.id)
    if request.is_ajax():
        return HttpResponse(simplejson.dumps(list(ann_list)))
    return render_to_response('annotations/list.html',
                              {'annotation_list': ann_list})

def annotate_form(request, content_type_str, obj_id, position=None):
    """
    Renders an AJAX-friendly html form for submitting snippets.
    """
    ct = ContentType.objects.get(name=content_type_str)
    obj = ct.model_class().objects.get(id=obj_id)
    ann_list = Annotation.objects.filter(content_type=ct, object_id=obj.id, position=position)
    preform_data = {'commentor':request.user.id,
                    'content_type':ct.id,
                    'object_id':obj_id,
                    'date_added':datetime.datetime.now(),
                    'position':position}
    f = AnnotationModelForm(request.POST or None, initial=preform_data)
    if f.is_valid():
        if f.save():
            # valid
            return HttpResponseRedirect(obj.get_absolute_url())
        else:
            return render_to_response('annotations/inline_form.html',
                                      {'form':f,
                                       'content_type': ct.name,
                                       'obj_id': obj.id,
                                       'position': position,
                                       'annotation_list': ann_list,
                                       'annotation_object': obj})
    else:
        # invalid / new
        return render_to_response('annotations/inline_form.html',
                                  {'form':f,
                                   'content_type': ct.name,
                                   'obj_id': obj.id,
                                   'position': position,
                                   'annotation_list': ann_list,
                                   'annotation_object': obj})

codereview/apps/annotation/templates/annotations/inline_form.html
{% if annotation_list %}
  <h4>Other Comments</h4>
  <ul>
    {% for annotation in annotation_list %}
      <li>{{ annotation.comment }} by {{ annotation.commentor }}</li>
    {% endfor %}
  </ul>
{% endif %}
<form method="POST" action="{% url annotate-form content_type,obj_id,position %}">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" />
</form>

codereview/templates/about/what_next.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}{% trans "What Next?" %}{% endblock %}

{% block body %}
    <h1>{% trans "What Next?" %}</h1>
    
    {% if user.is_authenticated %}
        <p>Here are some things to do to get started with this site:</p>
        
        <dl class="what_next">
            <dt><a href="{% url acct_email %}">verify an email address</a></dt>
            <dd>so you can receive notifications, reset your password and so people can find you more easily.</dd>
            
            <dt><a href="{% url profile_detail user %}">fill out your profile</a></dt>
            <dd>to tell the world a little about yourself.</dd>
            
            {% ifsetting ACCOUNT_OPEN_SIGNUP %}
            {% else %}
                {% if user.is_staff %}
                    <dt><a href="{% url admin_invite_user %}">invite more people to the site</a> [admin only]</dt>
                    <dd>so more people can share in the fun.</dd>
                {% endif %}
            {% endifsetting %}
        </dl>
        {% else %}
            {% url acct_login as login_url %}
            
            <p class="what_next">
                {% ifsetting ACCOUNT_OPEN_SIGNUP %}
                    {% url acct_signup as signup_url %}
                    {% blocktrans %}Start by <a href="{{ signup_url }}">signing up</a> and <a href="{{ login_url }}">logging in</a>.{% endblocktrans %}
                {% else %}
                    {% blocktrans %}Start by <a href="{{ login_url }}">logging in</a>.{% endblocktrans %}
                {% endifsetting %}
            </p>
        {% endif %}
{% endblock %}

codereview/templates/dpaste/base.html
{% extends "base.html" %}

{% block extra_head %}
{{ block.super }}
<style>
 pre span.numbers {
 	display: block;
	clear: both;
	text-align: right;
	padding-right: 10px;
	 
 }	
</style>
{% endblock %}

{% block body %}
    {% block headline %}{% endblock %}
    {% block content %}{% endblock %}
    {% block sidebar %}{% endblock %}
{% endblock %}

{% block extra_body %}
    {% block script_footer %}{% endblock %}
<script type="text/javascript" src="{{ STATIC_URL }}facebox/facebox.js"></script>
{% endblock %}

codereview/templates/dpaste/snippet_details.html
{% extends "dpaste/base.html" %}
{% load mptt_tags %}
{% load i18n %}
{% load annotation_tags %}

{% block extrahead %}
     {% if request.session.userprefs %}
     <style type="text/css" media="all">
         .code{
             {# FIXME: Thats stupid #}
             {% ifnotequal request.session.userprefs.font_family "None" %}font-family: {{ request.session.userprefs.font_family }} !important;{% endifnotequal %}
             {% ifnotequal request.session.userprefs.font_size "None" %}font-size: {{ request.session.userprefs.font_size }}px !important;{% endifnotequal %}
             {% ifnotequal request.session.userprefs.line_height "None" %}line-height: {{ request.session.userprefs.line_height }}px !important;{% endifnotequal %}
         }
     </style>
     {% endif %}
{% endblock %}

{% block title %}{% trans "Snippet" %} #{{ snippet.pk }}{% endblock %}
{% block headline %}
    <h1>
        {% trans "Snippet" %} #{{ snippet.pk }}
        {% if snippet.parent_id %}
            {% blocktrans with snippet.parent.get_absolute_url as parent_url and snippet.parent.id as parent_id %}(Copy of <a href="{{ parent_url }}">snippet #{{ parent_id }}</a>){% endblocktrans %}
        {% endif %}
        <span class="date">{{ snippet.published|date:_("DATETIME_FORMAT") }} ({% trans "UTC" %})</span>
    </h1>
{% endblock %}
{% load dpaste_tags %}

{% block content %}
<div id="diff" style="display:none;">diff</div>

<div class="accordion">
    <div class="snippet-options">
        <abbr title="{% trans "Time to life" %}">TTL:</abbr> {{ snippet.expires|timeuntil  }}
        &mdash;
        {% if snippet.pk|in_list:request.session.snippet_list %}
        <a onclick="return confirm('{% trans "Really delete this snippet?" %}')" href="{% url snippet_delete snippet.secret_id %}">Delete now!</a>
        &mdash;
        {% endif %}
        <a id="toggleWordwrap" href="#">{% trans "Wordwrap" %}</a>
    </div>
    <h2>
        {% if snippet.title %}{{ snippet.title }}{% else %} {% trans "Snippet" %} #{{ snippet.id}}{% endif %}
        <span>{% if snippet.author %}{% blocktrans with snippet.author as author %}by {{ author }}{% endblocktrans %}{% endif %}</span>
    </h2>

    <div class="container">
        <div class="snippet">
        <table>
            <tr>
                <th><pre class="code">{% for l in lines %}<span class="numbers"><a href="{% url annotate-form "snippet",snippet.id,forloop.counter %}" class="comment" rel="facebox" id="c{{ forloop.counter }}">C</a>&nbsp;&nbsp;<a href="#l{{ forloop.counter }}" id="l{{ forloop.counter }}">{{ forloop.counter }}</a></span>{% endfor %}</pre></th>
                <td><pre class="code">{% for line in snippet.content_splitted %}<div class="line" id="l{{ forloop.counter }}">{% if line %}{{ line|safe }}{% else %}&nbsp;{% endif %}</div>{% endfor %}</pre></td>
            </tr>
        </table>
        </div>
    </div>
	<ul>
        {% get_annotations snippet as annotation_list %}
		{% for comment in annotation_list %}
		  <li>{{ comment.comment }} by {{ comment.commentor }} at {{ comment.position }}</li>
		{% endfor %}
	</ul>
    <h2>{% trans "Write an answer" %} &rarr;</h2>
    <div class="container" style="display: none;">
        {% include "dpaste/snippet_form.html" %}
    </div>
</div>
{% endblock %}



{% block sidebar %}
    <h2>{% trans "History" %}</h2>

    <form method="get" id="diffform" action="{% url snippet_diff %}">
    <div class="tree">
        {% for tree_item,structure in tree|tree_info %}
        {% if structure.new_level %}<ul><li>{% else %}</li><li>{% endif %}
        <div>
        <span class="diff">
            <input type="radio" name="a" value="{{ tree_item.id }}" {% ifequal tree_item.id snippet.parent_id %}checked="checked"{% endifequal %}/>
            <input type="radio" name="b" value="{{ tree_item.id }}" {% ifequal snippet tree_item %}checked="checked"{% endifequal %}/>
        </span>
        {% ifequal snippet tree_item %}
            <strong>{% trans "Snippet" %} #{{ tree_item.id }}</strong>
       {% else %}
       <a href="{{ tree_item.get_absolute_url }}">{% trans "Snippet" %} #{{ tree_item.id }}</a>
        {% endifequal %}
        </div>
        {% for level in structure.closed_levels %}</li></ul>{% endfor %}
        {% endfor %}
        <div class="submit">
            <input type="submit" value="{% trans "Compare" %}"/>
        </div>
    </div>
    </form>

    <h2>{% trans "Options" %}</h2>
    <p><a href="{% url snippet_details_raw snippet.secret_id %}">{% trans "View raw" %}</a></p>
{% endblock %}

{% block script_footer %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.2/jquery-ui.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){

    curLine = document.location.hash;
    if(curLine.substring(0,2) == '#l'){
        $('div.snippet div.line'+curLine).addClass('marked');
    }

    $("div.accordion").accordion({
       autoHeight: false,
       header: 'h2',
       animation: 'bounceslide',
       duration: 2000,
    });

    /**
    * Diff Ajax Call
    */
    $("form#diffform").submit(function() {
        $.get("{% url snippet_diff %}", {
            a: $("input[name=a]:checked").val(),
            b: $("input[name=b]:checked").val()
        }, function(data){
            $('#diff').html(data).slideDown('fast');
        });
        return false;
    });

    /**
    * Wordwrap
    */
    $('#toggleWordwrap').toggle(
        function(){
            $('div.snippet pre.code').css('white-space', 'pre-wrap');
            return false;
        },
        function(){
            $('div.snippet pre.code').css('white-space', 'pre');
            return false;
        }
    );

    /**
    * Line Highlighting
    */
    $('div.snippet th a').each(function(i){
        $(this).click(function(){
            var j = $(this).text();
            $('div.snippet div.line.marked').removeClass('marked');
            $('div.snippet div.line#l'+j).toggleClass('marked');
        });
    });

    {% if request.session.userprefs.display_all_lexer %}
    /**
    * Lexer Guessing
    */
    $('#guess_lexer_btn').click(function(){
        $.getJSON('{% url snippet_guess_lexer %}',
            {'codestring': $('#id_content').val()},
            function(data){
                if(data.lexer == "unknown"){
                    $('#guess_lexer_btn').css('color', 'red');
                }else{
                    $('#id_lexer').val(data.lexer);
                    $('#guess_lexer_btn').css('color', 'inherit');
                }
            });
    });
    {% endif %}
});
</script>

<script type="text/javascript">
  var annotation_set = {% get_annotations_json snippet %};
  for (i=0;i<annotation_set.length;i++) {
    var pos = Number(annotation_set[i]['position']);
    var node = jQuery('#c'+pos);
    console.debug('adding: ', node[0], pos, annotation_set[i]);
    node.css('color', 'red');
    jQuery.data(node[0], 'comment', annotation_set[i]);
  }
</script>
{% endblock %}

codereview/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block tab_id %}id="home_tab"{% endblock %}

{% block body %}
    
    <h1>{% trans "Welcome to Pinax" %}</h1>
    
    <p>
        {% blocktrans %}
        <b>Pinax</b> is a <a href="http://djangoproject.com/">Django</a>
        project intended to provide a starting point for websites. By
        integrating numerous reusable Django apps to take care of the
        things that many sites have in common, it lets you focus on what
        makes your site different.
        {% endblocktrans %}
    </p>
    
    <p>
        {% blocktrans %}
        For more information about Pinax, see
        <a href="http://pinaxproject.com/">http://pinaxproject.com/</a>.
        {% endblocktrans %}
    </p>
    
    <h2>{% trans "About this project" %}</h2>
    
    <p>
        {% blocktrans %}
        This project comes with the bare minimum set of applications and
        templates to get you started. It includes no extra tabs, only the
        profile and notices tabs are included by default. From here you can
        add any extra functionality and applications that you would like.
        {% endblocktrans %}
    </p>
    
    <hr />
    {% if user.is_authenticated %}
        {% url what_next as what_next_url %}
        <p class="what_next">{% blocktrans %}Wondering <a href="{{ what_next_url }}">What Next</a>?{% endblocktrans %}</p>
    {% else %}
        {% url acct_login as login_url %}
        {% ifsetting ACCOUNT_OPEN_SIGNUP %}
            {% url acct_signup as signup_url %}
            <p>{% blocktrans %}You can <a href="{{ signup_url }}">Sign up</a> and <a href="{{ login_url }}">Log in</a> to try out the site.{% endblocktrans %}</p>
        {% else %}
            <p>{% blocktrans %}You can <a href="{{ login_url }}">Log in</a> to try out the site.{% endblocktrans %}</p>
        {% endifsetting %}
    {% endif %}
    
{% endblock %}

codereview/templates/site_base.html
{% extends "base.html" %}

{% load i18n %}
{% load account_tags %}
{% load openid_tags %}
{% load ifsetting_tag %}
{% load analytics %}

{% block extra_head_base %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/site_tabs.css" />
    {% block extra_head %}{% endblock %}
{% endblock %}

{% block login %}
    {% if user.is_authenticated %}
        {% openid_icon openid user %}<b>{% user_display user %}</b> | <a href="{% url acct_email %}">{% trans "Account" %}</a> | {% if user.is_staff %}<a href="/admin/">{% trans "Admin" %}</a> | {% endif %}<a href="/openid/logout/?next={% url acct_logout %}">{% trans "Logout" %}</a>
    {% else %}
        <a href="{% url acct_login %}">{% trans "Login" %}</a> {% ifsetting ACCOUNT_OPEN_SIGNUP %}{% trans "or" %} <a href="{% url acct_signup %}"><b>{% trans "Sign up" %}</b></a>{% endifsetting %}
    {% endif %}
{% endblock %}

{% block logo_link_image %}<a href="{% url home %}"><img src="{{ STATIC_URL }}pinax/images/logo.png" alt="Pinax"/></a>{% endblock %}

{% block right_tabs %}
    {% if user.is_authenticated %}
        <ul class="tabs">{% spaceless %}
            <li id="tab_profile"><a href="{% url profile_detail user %}">{% trans "Profile" %}</a></li>
            <li id="tab_notices"><a href="{% url notification_notices %}">{% trans "Notices" %}{% if notice_unseen_count %} ({{ notice_unseen_count }}){% endif %}</a></li>
        {% endspaceless %}</ul>
    {% endif %}
{% endblock %}

{% block footer %}
<div class="legal">
    {% trans "&copy; 2010 &lt;your company here&gt;" %}
    - <a href="{% url about %}">{% trans "About" %}</a>
    - <a href="{% url terms %}">{% trans "Terms of Service" %}</a>
    - <a href="{% url privacy %}">{% trans "Privacy Policy" %}</a>
    - <a href="{% url dmca %}">{% trans "DMCA Notice" %}</a>
</div>
{% endblock %}
{% block extra_body_base %}
    {% ga %}
{% endblock %}